### ISSUE TITLE
Run abaplint githubactoins in changed files

### ISSUE THREAD

**Issue by valeriast** [abaplint/actions-abaplint#25]
Hello,

I've been testing githubactions/abaplint and I've been trying to make it run only in changed files of a pull request. Is there a way to do it? The reason I'm searching for a solution to this is because the workflow runs on every file inside the repository and since it can only display 50 annotations sometimes the file changed in the PR shows no annotation because the annotation limit has already exceeded. 

Thanks and best regards

**Comment by larshp** [comment]
I recommend using https://github.com/marketplace/abaplint for a changed files concept

Also see https://help.sap.com/doc/936a5559809c4ab588a10bc5800d1461/Cloud/en-US/CICD_Introduction_Guide.pdf

> Keep your main line clean and do not accumulate errors.
> If you find that your code contains errors, for example, if one of your builds fails, make sure that you react on
> them immediately. Each error, once integrated into the main line, affects the entire development team and, at
> worst, prevents them from working. Also follow this principle when using voter builds to make sure that you
> don't accumulate more issues from change to change.

It sounds like the setup is not following the practice of fixing errors immediately and keeping the main line clean?

**Comment by valeriast** [comment]
Hello Lars,

Thanks for responding. We are now trying to implement abaplint in our workflow but we have many old projects that lacks clean code convention. With that in mind it would take a lot of effort to change all those lines of code at once. So our idea is to clean the code that we are currently refactoring/maintaining or working on. So being able to only get the findings from changed files would help us keep that workflow.

**Comment by larshp** [comment]
also see the discussion in https://github.com/abaplint/abaplint/issues/2678
